name: CI (triggers on ALL)
run-name: Gradle CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download and unzip Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip
          unzip gradle-8.2.1-bin.zip
          echo "${GITHUB_WORKSPACE}/gradle-8.2.1/bin" >> $GITHUB_PATH
      - name: Verify Gradle version
        run: gradle --version
      - name: Run the Gradle package task
        run: gradle build
