name: Continuous Integration
run-name: Gradle CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gradle-version: ['8.2.1']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install SDKMAN!
        run: curl -s "https://get.sdkman.io" | bash
      - name: Install specific Gradle version with SDKMAN!
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle ${{ matrix.gradle-version }}
      - name: Run the Gradle package task
        run: gradle build
