name: CI (On New Branch / On Push to Main)
run-name: CI (On New Branch / On Push to Main)


on:

  create:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    types:
      - opened

jobs:
  CI:
    uses: ./.github/workflows/ci.yml # reusable workflow file path

